import type {Metadata} from "next";



import "./globals.css";

export const metadata: Metadata = {
  title: "Generador-De-Descuentos",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased">
        <main>{children}</main>
      </body>
    </html>
  );
}
